[project]
name = "ciphercache"
version = "0.1.0"
description = "a local daemon providing secrets from a safe store"
requires-python = ">=3.12.0"
license = {file = "LICENSE"}
readme = "README.md"
authors = [{name = "@drakee"}]
keywords = ["secrets", "daemon", "keepassxc", "ipc"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Operating System :: MacOS",
]
urls = {Homepage = "https://github.com/drakee/ciphercache"}
dependencies = [
    "defusedxml>=0.7.1",
]

[tool.setuptools]
include-package-data = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py312"
line-length = 120
exclude = [
  ".git",
  ".venv",
  "venv",
  "build",
  "dist",
  "__pypackages__",
  ".mypy_cache",
  ".pytest_cache",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ipykernel>=7.1.0",
    "mypy>=1.11",
    "ruff>=0.14.14",
    "types-defusedxml>=0.7.0.20250822",
]

[project.scripts]
ciphercached = "ciphercache.daemon.runner:main"
